RSS_FEEDS = [
    # Trade & Banking Publications
    "https://www.tradefinanceglobal.com/feed/",
    "https://www.tradefinanceglobal.com/posts/category/articles/feed/",
    "https://www.tradefinanceglobal.com/posts/category/news/feed/",
    "https://www.tradefinanceglobal.com/posts/category/podcasts/feed/",
    "https://fintechnews.sg/payments/feed/",
    "https://fintechnews.sg/digital-banking-news-singapore/feed/",
    "https://fintechnews.sg/blockchain/feed/",
    "https://fintechnews.sg/digitalassets/feed/",
    "https://fintechnews.sg/regtech/feed/",
    "https://fintechnews.sg/ai/feed/",
    "https://fintechnews.id/payments/feed/",
    "https://fintechnews.id/digital-banking-news-singapore/feed/",
    "https://fintechnews.id/blockchain/feed/",
    "https://fintechnews.id/digitalassets/feed/",
    "https://fintechnews.id/regtech/feed/",
    "https://fintechnews.id/ai/feed/",
    "https://fintechnews.my/payments/feed/",
    "https://fintechnews.my/digital-banking-news-singapore/feed/",
    "https://fintechnews.my/blockchain/feed/",
    "https://fintechnews.my/digitalassets/feed/",
    "https://fintechnews.my/regtech/feed/",
    "https://fintechnews.my/ai/feed/",
    "https://fintechnews.ph/payments/feed/",
    "https://fintechnews.ph/digital-banking-news-singapore/feed/",
    "https://fintechnews.ph/blockchain/feed/",
    "https://fintechnews.ph/digitalassets/feed/",
    "https://fintechnews.ph/regtech/feed/",
    "https://fintechnews.ph/ai/feed/",
    "https://fintechnews.sg/thailand/feed/",
    "https://fintechnews.sg/vietnam/feed/",
    "https://www.pymnts.com/topic/fintech/feed/",
    "https://www.pymnts.com/topic/b2b/feed/",
    "https://www.pymnts.com/topic/crypto/feed/",
    "https://www.pymnts.com/topic/ai/feed/",
    "https://www.pymnts.com/topic/banking/feed/",
    "https://www.pymnts.com/topic/technology-regulation/feed/",
    "https://www.fintechfutures.com/category/bankingtech/feed/",
    "https://www.fintechfutures.com/category/paytech/feed/",
    "https://www.fintechfutures.com/category/regtech/feed/",
    "https://www.fintechfutures.com/category/wealthtech/feed/",
    "https://www.fintechfutures.com/category/lendtech/feed/",
    "https://www.fintechfutures.com/category/insurtech/feed/",
    "https://www.fintechfutures.com/us/region/asia-pacific/feed/",
    "https://www.finextra.com/rss/channel.aspx?channel=payments",
    "https://www.finextra.com/rss/channel.aspx?channel=ai",
    "https://www.finextra.com/rss/channel.aspx?channel=wholesale",
    "https://www.finextra.com/rss/channel.aspx?channel=regulation",
    "https://www.finextra.com/rss/channel.aspx?channel=sustainable",
    "https://www.finextra.com/rss/channel.aspx?channel=crypto",
    "https://www.finextra.com/rss/channel.aspx?channel=identity",
    "https://www.finextra.com/rss/channel.aspx?channel=security",
    "https://theasianbanker.com/category/technology/feed/",
    "https://theasianbanker.com/category/payments/feed/",
    "https://theasianbanker.com/category/banking/feed/",
    "https://theasianbanker.com/category/wholesale-banking/feed/",
    "https://theasianbanker.com/category/digital-banking/feed/",
    "https://theasianbanker.com/category/regulation/feed/",
    "https://www.financemagnates.com/fintech/feed/",
    "https://www.financemagnates.com/fintech/payments/feed/",
    "https://www.financemagnates.com/cryptocurrency/feed/",
    "https://www.financemagnates.com/institutional-forex/feed/",
    "https://www.financemagnates.com/thought-leadership/feed/",
    "https://www.techinasia.com/tag/fintech/feed",
    "https://www.techinasia.com/tag/southeast-asia/feed",
    "https://www.techinasia.com/tag/indonesia/feed",
    "https://www.techinasia.com/tag/singapore/feed",
    "https://www.techinasia.com/tag/malaysia/feed",
    "https://www.techinasia.com/tag/philippines/feed",
    "https://www.paymentsdive.com/feeds/news?topic=banking",
    "https://www.paymentsdive.com/feeds/news?topic=technology",
    "https://www.paymentsdive.com/feeds/news?topic=b2b",
    "https://www.paymentsdive.com/feeds/news?topic=regulations_and_policy",
    "https://www.paymentsdive.com/feeds/news?topic=risk",
    "https://thepaypers.com/rss/payments",
    "https://thepaypers.com/rss/ecommerce",
    "https://thepaypers.com/rss/fintech",
    "https://thepaypers.com/rss/cryptocurrencies",
    "https://thepaypers.com/rss/open-banking",
    "https://thepaypers.com/rss/digital-identity",
    "https://thepaypers.com/rss/fraud-security",
    "https://asianbankingandfinance.net/banking/feed/",
    "https://asianbankingandfinance.net/technology/feed/",
    "https://thefintechtimes.com/category/payments/feed/",
    "https://thefintechtimes.com/category/blockchain/feed/",
    "https://thefintechtimes.com/category/regtech/feed/",
    "https://thefintechtimes.com/category/asia/feed/",
    "https://thefintechtimes.com/category/fintech/feed/",
    "https://thefintechtimes.com/category/artificial-intelligence/feed/",
    "https://www.bobsguide.com/feed/",
    "https://www.bobsguide.com/category/banking-technology/feed/",
    "https://www.bobsguide.com/category/payments/feed/",
    "https://www.bobsguide.com/category/regtech/feed/",
    "https://www.bobsguide.com/category/fintech/feed/",

    # Regulatory Bodies
    "https://www.bnm.gov.my/rss",
    "https://www.bsp.gov.ph/_layouts/15/listfeed.aspx?List=68408d09-548e-40f5-b2fd-62d36e30fd3f&View=5580f386-ff60-40ff-8531-2b5259079a97",

    # Competitor Newsrooms
    "https://www.jpmorganchaseco.gcs-web.com/rss/news-releases.xml",
    "https://www.ocbc.com/group/news/rss.xml",

    # Consultants & Advisory — RSS
    "https://www.mckinsey.com/industries/financial-services/our-insights/rss",
    "https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/rss",
    "https://www.mckinsey.com/featured-insights/asia-pacific/rss",
    "https://www2.deloitte.com/us/en/insights/industry/financial-services/rss.xml",
    "https://www2.deloitte.com/us/en/insights/topics/digital-transformation/rss.xml",
    "https://www2.deloitte.com/us/en/insights/economy/asia-pacific/rss.xml",
    "https://www.pwc.com/gx/en/news-room/rss.html",
    "https://www.pwc.com/gx/en/industries/financial-services/fintech/rss.html",
    "https://www.ey.com/en_gl/insights/financial-services/rss",
    "https://www.ey.com/en_gl/insights/banking-capital-markets/rss",
    "https://www.ey.com/en_gl/insights/payments/rss",
    "https://kpmg.com/xx/en/blogs/home/rss.xml",
    "https://kpmg.com/xx/en/home/insights/rss.xml",
    "https://www.oliverwyman.com/our-expertise/industries/financial-services/rss.xml",
    "https://www.oliverwyman.com/our-expertise/regions/asia-pacific/rss.xml",
    "https://www.bcg.com/rss/publications",
    "https://www.bcg.com/industries/financial-institutions/rss",
    "https://newsroom.accenture.com/rss/news.xml",
    "https://www.accenture.com/us-en/insights/banking/rss",
    "https://www.accenture.com/us-en/insights/financial-services/rss",
    "https://www.bis.org/rss/work.htm",
    "https://www.bis.org/rss/qtrly.htm",
    "https://www.bis.org/rss/fsi_papers.htm",
    "https://blogs.worldbank.org/allblogs/rss.xml",
    "https://www.adb.org/rss/publications.xml",
    "https://www.adb.org/rss/news.xml",
    "https://www.imf.org/en/Publications/RSS",
    "https://www.swift.com/swift-resource/rss",
    "https://www.swift.com/news-events/news/rss",
]

SCRAPE_URLS = [
    # Competitor cash management product pages
    "https://www.dbs.com.sg/corporate/solutions/cash-management",
    "https://www.jpmorgan.com/payments/solutions/treasury",
    "https://www.jpmorgan.com/global-corporate-banking",
    "https://www.jpmorgan.com/payments/payments-apac",
    "https://www.jpmorgan.com/international-banking",
    "https://www.jpmorgan.com/payments/solutions/access",
    "https://www.jpmorgan.com/payments/solutions/treasury/liquidity",
    "https://www.business.hsbc.com.sg/en-sg/corporate-banking",
    "https://www.business.hsbc.com/en-gb/products/transaction-banking",
    "https://www.business.hsbc.com/en-gb/products-and-solutions",
    "https://www.business.hsbc.com.sg/en-sg/solutions/hsbc-omni-collect",
    "https://www.business.hsbc.com.sg/en-sg/solutions/payments-clearing-and-foreign-currency-payments",
    "https://www.business.hsbc.com.sg/en-sg/solutions/hsbc-commercial-cards-programme",
    "https://www.sc.com/en/corporate-investment-banking/transaction-banking/",
    "https://www.sc.com/en/corporate-investment-banking/",
    "https://www.sc.com/en/support-centre/",
    "https://www.business.hsbc.com/en-gb/products/liquidity-management-portal-lmp",
    "https://www.business.hsbc.com/en-gb/products/cash-flow-forecasting",
    "https://www.business.hsbc.com/en-gb/solutions/payments",
    "https://www.business.hsbc.com/en-gb/products/liquidity-and-investments",
    "https://www.business.hsbc.com.sg/en-sg/solutions/payments-liquidity-liability-and-investments",
    "https://www.citi.com/small-business-banking/cash-management",
    "https://www.citidirect.com/cdhome",
    "https://corporates.db.com/solutions/corporate-bank-solutions/cash-management/",
    "https://corporates.db.com",
    "https://www.dbs.bank.in/in/corporate/solutions/digital/cash-management-digitalisation",
    "https://www.bangkokbank.com/en/Business-Banking/Manage-My-Business/Digital-Banking/iCash-NewSystem",
    "https://www.bca.co.id/en/bisnis/solusi/cash-management",

    # Consultant Insights Pages — scrape for PDF links and articles
    "https://www.mckinsey.com/industries/financial-services/our-insights",
    "https://www.mckinsey.com/featured-insights/asia-pacific",
    "https://www2.deloitte.com/us/en/insights/industry/financial-services.html",
    "https://www2.deloitte.com/ap/en/pages/financial-services/topics/banking.html",
    "https://www.pwc.com/gx/en/industries/financial-services/publications.html",
    "https://www.pwc.com/gx/en/industries/financial-services/fintech.html",
    "https://www.ey.com/en_gl/insights/banking-capital-markets",
    "https://www.ey.com/en_gl/insights/payments",
    "https://www.ey.com/en_ap/insights",
    "https://kpmg.com/xx/en/home/insights.html",
    "https://kpmg.com/sg/en/home/insights.html",
    "https://www.oliverwyman.com/our-expertise/industries/financial-services.html",
    "https://www.oliverwyman.com/our-expertise/regions/asia-pacific.html",
    "https://www.bcg.com/industries/financial-institutions/banking",
    "https://www.bcg.com/industries/financial-institutions/transaction-banking",
    "https://www.accenture.com/us-en/insights/banking",
    "https://www.accenture.com/us-en/insights/financial-services",
    "https://www.accenture.com/sg-en/insights/banking",
    "https://www.bis.org/publ/work.htm",
    "https://www.bis.org/cpmi/publications.htm",
    "https://www.adb.org/publications/series/trade-finance",
    "https://www.adb.org/publications/series/working-paper-series",
    "https://www.swiftinstitute.org/research/",
    "https://www.greenwich.com/transaction-banking",
    "https://www.greenwich.com/cash-management",
]

# Direct PDF URLs — known consultant and regulatory reports
# Add any PDF links you find manually here and they will be
# downloaded and extracted automatically on every pipeline run
PDF_URLS = [
    # BIS Papers
    "https://www.bis.org/publ/work1101.pdf",
    "https://www.bis.org/cpmi/publ/d187.pdf",
    "https://www.bis.org/publ/arpdf/ar2024e.pdf",

    # IMF Working Papers
    "https://www.imf.org/en/Publications/WP/Issues/2024/01/19/",

    # ADB
    "https://www.adb.org/sites/default/files/publication/922096/trade-finance-gaps-growth-jobs-survey-2023.pdf",

    # MAS
    "https://www.mas.gov.sg/publications/annual-reports/2023",

    # Swift
    "https://www.swift.com/swift-resource/251786/download",
]